web:
    static_path:
    host: 192.168.60.251
    port: 8087
    domain: 192.168.60.251:8087
    read_timeout: 5
    write_timeout: 5
    idle_timeout: 5
gorm:
    debug: true
    db_type: mysql
    max_lifetime: 7200
    max_open_conns: 150
    max_idle_conns: 50
    table_prefix: tb_
mysql:
    host: 127.0.0.1
    port: 3306
    user: root
    password: zchainbtc
    db_name: webmanage
    parameters: charset=utf8&parseTime=True&interpolateParams=true
postgresql:
    host: 127.0.0.1
    port: 5432
    user: root
    password: zchainbtc
    db_name: webmanage
    parameters: charset=utf8&parseTime=True&loc=Asia%2FShanghai
sqlite3:
    path: data/goapp.db


